repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
        files: ^perun/
        types: [ file, python ]
    -   id: trailing-whitespace
        files: ^perun/
        types: [ file, python ]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        files: ^perun/
        types: [file, python]
